// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bomqynyzztbibggernde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvbXF5bnl6enRiaWJnZ2VybmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDMyNjYsImV4cCI6MjA2NTcxOTI2Nn0.oJKNn_bO5R_Wkhc3JDEQLm-C8rI0iD_V1k1BvzaeNF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);